/*
 * app_config.h
 *
 * Created: 2023-08-05 3:29:48 AM
 *  Author: HAZEM-PC
 */ 

#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

/*=========FILE INCLUSION=========*/


/*=========CONFIGURATION PARAMETERS=========*/
#define START_BUTTON_PORT
#define START_BUTTON_PIN

#define STOP_BUTTON_PORT
#define STOP_BUTTON_PIN

#define DIRECTION_BUTTON_PORT			PORTC_ID
#define DIRECTION_BUTTON_PIN			PIN7_ID

#define RIGHT_UP_WHEEL_PORT				PORTD_ID
#define RIGHT_UP_WHEEL_POSITIVE_PIN		PIN0_ID
#define RIGHT_UP_WHEEL_NEGATIVE_PIN		PIN1_ID

#define RIGHT_DOWN_WHEEL_PORT			PORTD_ID
#define RIGHT_DOWN_WHEEL_POSITIVE_PIN	PIN2_ID
#define RIGHT_DOWN_WHEEL_NEGATIVE_PIN	PIN3_ID

#define LEFT_UP_WHEEL_PORT				PORTD_ID
#define LEFT_UP_WHEEL_POSITIVE_PIN		PIN4_ID
#define LEFT_UP_WHEEL_NEGATIVE_PIN		PIN5_ID

#define LEFT_DOWN_WHEEL_PORT			PORTD_ID
#define LEFT_DOWN_WHEEL_POSITIVE_PIN	PIN6_ID
#define LEFT_DOWN_WHEEL_NEGATIVE_PIN	PIN7_ID	

#define DC_MOTOR_ENABLE_PORT			PORTB_ID
#define DC_MOTOR_ENABLE_PIN				PIN7_ID

#define ULTRASONIC_PORT					PORTB_ID
#define ULTRASONIC_TRIGGER_PIN			PIN3_ID
#define ULTRASONIC_ECHO_PIN				PIN2_ID

//application parameters
#define TIMEOUT_TIMER_ID				0
#define DELAY_TIMER_ID					2
#define WAIT_TIME_SEC					2
#define DISTANCE_TIMEOUT_SEC			5
#define DIRECTION_TIMEOUT_SEC			5
#define ROBOT_STOP_TIME_SEC				3
#define _70_CM							70
#define _30_CM							30
#define _20_CM							20
#define SPEED_50_PERCENT				50
#define SPEED_30_PERCENT				30







#endif /* APP_CONFIG_H_ */